apps/scout/scout/server/blueprints/cases/views.py
# -*- coding: utf-8 -*-
import datetime
import io
import logging
import os.path
import pathlib
import re
import shutil
import zipfile
from operator import itemgetter

import pymongo
from flask import (
    Blueprint,
    abort,
    current_app,
    flash,
    jsonify,
    redirect,
    render_template,
    request,
    send_file,
    send_from_directory,
    Response,
    url_for,
)

from flask_login import current_user
from flask_weasyprint import HTML, render_pdf
from werkzeug.datastructures import Headers

from scout.constants import SAMPLE_SOURCE
from scout.server.extensions import mail, store
from scout.server.utils import institute_and_case, templated, user_institutes

from . import controllers

LOG = logging.getLogger(__name__)

cases_bp = Blueprint(
    "cases",
    __name__,
    template_folder="templates",
    static_folder="static",
    static_url_path="/cases/static",
)


@cases_bp.route("/institutes")
@templated("cases/index.html")
def index():
    """Display a list of all user institutes."""
    institute_objs = user_institutes(store, current_user)
    institutes_count = (
        (institute_obj, store.cases(collaborator=institute_obj["_id"]).count())
        for institute_obj in institute_objs
        if institute_obj
    )
    return dict(institutes=institutes_count)


@cases_bp.route("/<institute_id>/<case_name>")
@templated("cases/case.html")
def case(institute_id, case_name):
    """Display one case."""
    institute_obj, case_obj = institute_and_case(store, institute_id, case_name)
    if not case_obj:
        flash("Case {} does not exist in database!".format(case_name))
        return redirect(request.referrer)

    data = controllers.case(store, institute_obj, case_obj)
    return dict(
        institute=institute_obj,
        case=case_obj,
        mme_nodes=current_app.mme_nodes,
        tissue_types=SAMPLE_SOURCE,
        **data,
    )


@cases_bp.route("/<institute_id>/<case_name>/sma", methods=["GET"])
@templated("cases/case_sma.html")
def sma(institute_id, case_name):
    """Visualize case SMA data - SMN CN calls"""
    institute_obj, case_obj = institute_and_case(store, institute_id, case_name)
    data = controllers.case(store, institute_obj, case_obj)
    return dict(institute=institute_obj, case=case_obj, format="html", **data)


@cases_bp.route("/<institute_id>/<case_name>/mme_matches", methods=["GET", "POST"])
@templated("cases/matchmaker.html")
def matchmaker_matches(institute_id, case_name):
    """Show all MatchMaker matches for a given case"""
    # check that only authorized users can access MME patients matches
    panel = 1
    if request.method == "POST":
        panel = panel = request.form.get("pane_id")
    user_obj = store.user(current_user.email)
    if "mme_submitter" not in user_obj["roles"]:
        flash("unauthorized request", "warning")
        return redirect(request.referrer)
    # Required params for getting matches from MME server:
    mme_base_url = current_app.config.get("MME_URL")
    mme_token = current_app.config.get("MME_TOKEN")
    if not mme_base_url or not mme_token:
        flash(
            "An error occurred reading matchmaker connection parameters. Please check config file!",
            "danger",
        )
        return redirect(request.referrer)
    institute_obj, case_obj = institute_and_case(store, institute_id, case_name)
    data = controllers.mme_matches(case_obj, institute_obj, mme_base_url, mme_token)
    data["panel"] = panel
    if data and data.get("server_errors"):
        flash(
            "MatchMaker server returned error:{}".format(data["server_errors"]), "danger",
        )
        return redirect(request.referrer)
    if not data:
        data = {"institute": institute_obj, "case": case_obj, "panel": panel}
    return data


@cases_bp.route("/<institute_id>/<case_name>/mme_match/<target>", methods=["GET", "POST"])
def matchmaker_match(institute_id, case_name, target):
    """Starts an internal match or a match against one or all MME external nodes"""
    institute_obj, case_obj = institute_and_case(store, institute_id, case_name)

    # check that only authorized users can run matches
    user_obj = store.user(current_user.email)
    if "mme_submitter" not in user_obj["roles"]:
        flash("unauthorized request", "warning")
        return redirect(request.referrer)

    # Required params for sending an add request to MME:
    mme_base_url = current_app.config.get("MME_URL")
    mme_accepts = current_app.config.get("MME_ACCEPTS")
    mme_token = current_app.config.get("MME_TOKEN")
    nodes = current_app.mme_nodes

    if not mme_base_url or not mme_token or not mme_accepts:
        flash(
            "An error occurred reading matchmaker connection parameters. Please check config file!",
            "danger",
        )
        return redirect(request.referrer)

    match_results = controllers.mme_match(
        case_obj, target, mme_base_url, mme_token, nodes, mme_accepts
    )
    ok_responses = 0
    for match_results in match_results:
        if match_results["status_code"] == 200:
            ok_responses += 1
    if ok_responses:
        flash("Match request sent. Look for eventual matches in 'Matches' page.", "info")
    else:
        flash("An error occurred while sending match request.", "danger")

    return redirect(request.referrer)


@cases_bp.route("/<institute_id>/<case_name>/mme_add", methods=["POST"])
def matchmaker_add(institute_id, case_name):
    """Add or update a case in MatchMaker"""

    # check that only authorized users can add patients to MME
    user_obj = store.user(current_user.email)
    if "mme_submitter" not in user_obj["roles"]:
        flash("unauthorized request", "warning")
        return redirect(request.referrer)

    institute_obj, case_obj = institute_and_case(store, institute_id, case_name)
    causatives = False
    features = False
    if case_obj.get("suspects") and len(case_obj.get("suspects")) > 3:
        flash(
            "At the moment it is not possible to save to MatchMaker more than 3 pinned variants",
            "warning",
        )
        return redirect(request.referrer)
    if case_obj.get("suspects"):
        causatives = True
    if case_obj.get("phenotype_terms"):
        features = True

    mme_save_options = ["sex", "features", "disorders"]
    for index, item in enumerate(mme_save_options):
        if item in request.form:
            LOG.info("item {} is in request form".format(item))
            mme_save_options[index] = True
        else:
            mme_save_options[index] = False
    genomic_features = request.form.get("genomicfeatures")
    genes_only = True  # upload to matchmaker only gene names
    if genomic_features == "variants":
        genes_only = False  # upload to matchmaker both variants and gene names

    # If there are no genomic features nor HPO terms to share for this case, abort
    if (not case_obj.get("suspects") and not mme_save_options[1]) or (
        causatives is False and features is False
    ):
        flash(
            "In order to upload a case to MatchMaker you need to pin a variant or at least assign a phenotype (HPO term)",
            "danger",
        )
        return redirect(request.referrer)

    user_obj = store.user(current_user.email)

    # Required params for sending an add request to MME:
    mme_base_url = current_app.config.get("MME_URL")
    mme_accepts = current_app.config.get("MME_ACCEPTS")
    mme_token = current_app.config.get("MME_TOKEN")

    if not mme_base_url or not mme_accepts or not mme_token:
        flash(
            "An error occurred reading matchmaker connection parameters. Please check config file!",
            "danger",
        )
        return redirect(request.referrer)

    add_result = controllers.mme_add(
        store=store,
        user_obj=user_obj,
        case_obj=case_obj,
        add_gender=mme_save_options[0],
        add_features=mme_save_options[1],
        add_disorders=mme_save_options[2],
        genes_only=genes_only,
        mme_base_url=mme_base_url,
        mme_accepts=mme_accepts,
        mme_token=mme_token,
    )

    # flash MME responses (one for each patient posted)
    n_succes_response = 0
    n_inserted = 0
    n_updated = 0
    category = "warning"

    for resp in add_result["server_responses"]:
        message = resp.get("message")
        if resp.get("status_code") == 200:
            n_succes_response += 1
        else:
            flash(
                "an error occurred while adding patient to matchmaker: {}".format(message),
                "warning",
            )
        if message == "Patient was successfully updated.":
            n_updated += 1
        if message == "Patient was successfully inserted into database.":
            n_inserted += 1

    # if at least one patient was inserted or updated into matchmaker, save submission at the case level:
    if n_inserted or n_updated:
        category = "success"
        store.case_mme_update(case_obj=case_obj, user_obj=user_obj, mme_subm_obj=add_result)
    flash(
        "Number of new patients in matchmaker:{0}, number of updated records:{1}, number of failed requests:{2}".format(
            n_inserted, n_updated, len(add_result.get("server_responses")) - n_succes_response,
        ),
        category,
    )

    return redirect(request.referrer)


@cases_bp.route("/<institute_id>/<case_name>/mme_delete", methods=["POST"])
def matchmaker_delete(institute_id, case_name):
    """Remove a case from MatchMaker"""

    # check that only authorized users can delete patients from MME
    user_obj = store.user(current_user.email)
    if "mme_submitter" not in user_obj["roles"]:
        flash("unauthorized request", "warning")
        return redirect(request.referrer)

    institute_obj, case_obj = institute_and_case(store, institute_id, case_name)
    # Required params for sending a delete request to MME:
    mme_base_url = current_app.config.get("MME_URL")

apps/scout/scout/server/blueprints/diagnoses/views.py
from flask import Blueprint

from scout.server.extensions import store
from scout.server.utils import templated, public_endpoint
from . import controllers

omim_bp = Blueprint("diagnoses", __name__, template_folder="templates")


@omim_bp.route("/diagnoses/<omim_nr>", methods=["GET"])
@templated("diagnoses/omim_term.html")
def omim_diagnosis(omim_nr):
    """Display information specific to one OMIM diagnosis"""

    data = controllers.omim_entry(store, omim_nr)
    return data


@omim_bp.route("/diagnoses", methods=["GET"])
@templated("diagnoses/omim_terms.html")
def omim_diagnoses():
    """Display all OMIM diagnoses available in database"""

    data = {"terms": store.disease_terms()}
    return data

apps/scout/scout/server/blueprints/genes/views.py
# -*- coding: utf-8 -*-
from flask import abort, Blueprint, request, jsonify, redirect, url_for, flash

from scout.server.extensions import store
from scout.server.utils import templated, public_endpoint
from . import controllers

genes_bp = Blueprint("genes", __name__, template_folder="templates")


@genes_bp.route("/genes")
@templated("genes/genes.html")
def genes():
    """Render seach box for genes."""
    query = request.args.get("query", "")
    hgnc_id = None
    if "|" in query:
        try:
            hgnc_id = int(query.split(" | ", 1)[0])
        except ValueError:
            flash("Provided gene info could not be parsed!", "warning")
    if hgnc_id:
        return redirect(url_for(".gene", hgnc_id=hgnc_id))
    gene_q = store.all_genes(limit=20)
    return dict(genes=gene_q)


@genes_bp.route("/genes/<int:hgnc_id>")
@genes_bp.route("/genes/<hgnc_symbol>")
@templated("genes/gene.html")
def gene(hgnc_id=None, hgnc_symbol=None):
    """Render information about a gene."""
    if hgnc_symbol:
        res = [gene for gene in store.hgnc_genes(hgnc_symbol)]
        if len(res) == 1:
            hgnc_id = res[0]["hgnc_id"]
        else:
            return redirect(url_for(".genes", query=hgnc_symbol))
    try:
        genes = controllers.gene(store, hgnc_id)
    except ValueError as error:
        return abort(404)

    return genes


@genes_bp.route("/api/v1/genes")
@public_endpoint
def api_genes():
    """Return JSON data about genes."""
    query = request.args.get("query")
    json_out = controllers.genes_to_json(store, query)
    return jsonify(json_out)

apps/scout/scout/server/blueprints/login/views.py
# -*- coding: utf-8 -*-
from datetime import datetime

from flask import (
    abort,
    current_app,
    Blueprint,
    flash,
    redirect,
    request,
    session,
    url_for,
    render_template,
)
from flask_login import login_user, logout_user
from flask_ldap3_login.forms import LDAPLoginForm
from flask_ldap3_login import AuthenticationResponseStatus

from scout.server.extensions import login_manager, store, ldap_manager, oauth_client
from scout.server.utils import public_endpoint
from . import controllers
from .models import LoginUser, LdapUser

import logging

LOG = logging.getLogger(__name__)

login_bp = Blueprint(
    "login",
    __name__,
    template_folder="templates",
    static_folder="static",
    static_url_path="/login/static",
)

login_manager.login_view = "login.login"
login_manager.login_message = "Please log in to access this page."
login_manager.login_message_category = "info"

ldap_users = {}  # used by ldap save_user


@login_manager.user_loader
def load_user(user_id):
    """Returns the currently active user as an object."""
    user_obj = store.user(user_id)
    user_inst = LoginUser(user_obj) if user_obj else None
    return user_inst


@login_bp.route("/login", methods=["GET", "POST"])
@public_endpoint
def login():
    """Login a user if they have access."""
    if "next" in request.args:
        session["next_url"] = request.args["next"]

    user_id = None
    user_mail = None
    if current_app.config.get("LDAP_HOST") and request.method == "POST":
        form = LDAPLoginForm()
        LOG.info("Validating LDAP user")
        if not form.validate_on_submit():
            flash("username-password combination is not valid, plase try again", "warning")
            return redirect(url_for("public.index"))
        user_id = form.username.data

    if current_app.config.get("GOOGLE"):
        if session.get("email"):
            user_mail = session["email"]
            session.pop("email", None)
        else:
            LOG.info("Google Login!")
            redirect_uri = url_for(".authorized", _external=True)
            try:
                return oauth_client.google.authorize_redirect(redirect_uri)
            except Exception as ex:
                flash("An error has occurred while logging in user using Google OAuth")

    if request.args.get("email"):  # log in against Scout database
        user_mail = request.args.get("email")
        LOG.info("Validating user {} against Scout database".format(user_id))

    user_obj = store.user(email=user_mail, user_id=user_id)
    if user_obj is None:
        flash("User not whitelisted", "warning")
        return redirect(url_for("public.index"))

    user_obj["accessed_at"] = datetime.now()
    if session.get("name"):  # These args come from google auth
        user_obj["name"] = session.get("name")
        user_obj["locale"] = session.get("locale")
    store.update_user(user_obj)

    user_dict = LoginUser(user_obj)
    return perform_login(user_dict)


@login_bp.route("/authorized")
@public_endpoint
def authorized():
    """Google auth callback function"""
    token = oauth_client.google.authorize_access_token()
    google_user = oauth_client.google.parse_id_token(token)
    session["email"] = google_user.get("email").lower()
    session["name"] = google_user.get("name")
    session["locale"] = google_user.get("locale")

    return redirect(url_for(".login"))


@login_bp.route("/logout")
def logout():
    logout_user()
    session.pop("email", None)
    session.pop("name", None)
    session.pop("locale", None)
    flash("you logged out", "success")
    return redirect(url_for("public.index"))


@login_bp.route("/users")
def users():
    """Show all users in the system."""
    data = controllers.users(store)
    return render_template("login/users.html", **data)


def perform_login(user_dict):
    if login_user(user_dict, remember=True):
        flash("you logged in as: {}".format(user_dict.name), "success")
        next_url = session.pop("next_url", None)
        return redirect(request.args.get("next") or next_url or url_for("cases.index"))
    flash("sorry, you could not log in", "warning")
    return redirect(url_for("public.index"))


@ldap_manager.save_user
def save_user(dn, username, data, memberships):
    user = LdapUser(dn, username, data)
    ldap_users[dn] = user
    return user

apps/scout/scout/server/templates/bootstrap4.html
<!DOCTYPE html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="shortcut icon" href="{{url_for('public.favicon')}}">

	{% block css %}
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="{{ url_for('static', filename='bs4_styles.css') }}">
	{% endblock %}

	{% block css_style %}
  {% endblock %}
</head>

<body>
	{% block body %}
  {% block navbar%}
  {% endblock navbar%}
	{% block content %}
  {% endblock content%}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  {% block scripts %}
	<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
	{% endblock scripts %}

	{% endblock body %}

</body>
</html>

apps/scout/scout/server/templates/layout_bs4.html
{% extends "bootstrap4.html" %}

{% block title %}
  {% if title %}
    {{ title }} - Scout
  {% else %}
    Welcome to Scout
  {% endif %}
{% endblock title %}

{% block styles %}
  {{ super() }}
{% endblock %}

{% block head %}
  {{ super() }}
{% endblock head %}

{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-inverse">
      <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('cases.index') }}">
          <img src="{{ url_for('public.static', filename='scout-logo.png') }}" width="30" height="30" class="d-inline-block align-top" alt=""><font color="white">Scout</font></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="fa fa-bars"></span>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{{ url_for('public.index') }}">Home</a>
                <a class="dropdown-item" href="{{ url_for('genes.genes') }}">Genes</a>
                <a class="dropdown-item" href="{{ url_for('panels.panels') }}">Gene Panels</a>
                <a class="dropdown-item" href="{{ url_for('phenotypes.hpo_terms') }}">Phenotypes</a>
                <a class="dropdown-item" href="{{ url_for('diagnoses.omim_diagnoses') }}">Diagnoses</a>
                <a class="dropdown-item" href="{{ url_for('login.users') }}">Users</a>
                <a class="dropdown-item" href="{{ url_for('overview.institutes') }}">Institutes</a>
                <a class="dropdown-item" href="{{ url_for('dashboard.index') }}">Dashboard</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="http://www.clinicalgenomics.se/scout/" target='_blank'>User guide</a>
                <a class="dropdown-item" href="https://github.com/Clinical-Genomics/scout/issues" target='_blank'>Open issues</a>
              </div>
            </li>
            {% block top_nav %}{% endblock %}
          </ul>
          <ul class="navbar-nav navbar-right">
            {% block top_nav_right %}
              {% if current_user.is_authenticated %}
                <li class="nav-item dropdown">
                  <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">{{ current_user.name }} <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li>
                      <a class="dropdown-item" href="{{ url_for('login.logout') }}">Logout</a>
                    </li>
                  </ul>
                </li>
              {% endif %}
            {% endblock %}
          </ul>
        </div>
      </div>
    </nav>
{% endblock %}

{% block content %}
  <div class="container-fluid">
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          <div class="alert alert-{{ category or 'primary' }} alert-dismissible fade show mt-3" role="alert">
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
    {% endwith %}

  {# application content needs to be provided in the content_main block #}
  {% block content_main %}{% endblock %}
  </div>
{% endblock %}

apps/scout/scout/server/templates/report_base.html
<!DOCTYPE html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

	{% block css %}
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	{% endblock %}

	{% block css_style %}{% endblock %}
</head>
<body>
	{% block body %}
	{% block content_main %}
	{% endblock %}
	{% endblock %}

	{% block scripts %}
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
	{% endblock %}
</body>
</html>

apps/scout/scout/server/templates/utils.html
{% macro comments_table(institute, case, comments, variant_id=None) %}
  <table class='table table-bordered table-hover table-condensed'>
    <thead>
      <tr>
	<th>User</th>
	<th>Comment</th>
      </tr>
    </thead>
    <tbody>
      {% for comment in comments %}
      <tr>
      	<td>
      	  <small>
      	    <strong> {{ comment.user_name }} </strong>
      	    on {{ comment.created_at.date() }}
      	    {% if comment.level == 'global' %}
                    <span class='badge badge-info'>GLOBAL</span>
                  {% endif %}
      	    {% if comment.created_at < case.updated_at %}
                    <span class='badge badge-warning'>OLD</span>
                  {% endif %}
      	  </small>
      	</td>
      	<td>
      	  {{ comment.content }}
      	</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endmacro %}

{% macro comments_panel(institute, case, current_user, comments, variant_id=None) %}
  <div class="card panel-default">
    <div class="panel-heading">Comments</div>
    <div class="card-body">
      <div class="list-group" style="max-height:200px; overflow-y: scroll;">
        {% for comment in comments %}
          <a class="list-group-item">
            <div class="row">
              <div class="col-xs-12 text-break">{{ comment.content }}</div>
            </div>
            <div class="row">
              <div class="d-flex justify-content-between align-items-center">
                <form method="POST" action="{{ url_for('cases.events', institute_id=institute._id, case_name=case.display_name, event_id=comment._id) }}">
                  <small>
                    <br>
                    <strong>{{ comment.user_name }}</strong>
                    on {{ comment.created_at.date() }}
                    {% if comment.level == 'global' %}
                      <span class="badge badge-info">GLOBAL</span>
                    {% endif %}
                    {% if comment.created_at < case.updated_at %}
                      <span class="badge badge-warning">OLD</span>
                    {% endif %}
                    {% if comment.user_id == current_user.email %}
                      <button class="btn btn-link btn-sm" type="submit"><i class="fa fa-remove"></i></button>
                    {% endif %}
                  </small>
                </form>
              </div>
            </div>
          </a>
        {% else %}
          <a class="list-group-item">No comments yet</a>
        {% endfor %}
      </div>
    </div>
    <div class="card-footer">
      <form action="{{ url_for('cases.events', institute_id=institute._id, case_name=case.display_name, variant_id=variant_id) }}" method="POST">
        <input type="hidden" name="link" value="{{ url_for('variant.variant', institute_id=institute._id, case_name=case.display_name, variant_id=variant_id) if variant_id else url_for('cases.case', institute_id=institute._id, case_name=case.display_name) }}">
        <div class="form-group">
          <textarea class="form-control" name="content" placeholder="Leave a comment"></textarea>
        </div>
        <div class="row">
          {% if variant_id %}
            <div class="col-sm-6">
              <div class="checkbox">
                <label>
                  <input type="checkbox" name="level" value="global">
                  Comment globally
                </label>
              </div>
            </div>
          {% endif %}
          <div class="col-sm-{{ 6 if variant_id else 12 }}">
            <button class="btn btn-outline-secondary form-control" type="submit">Comment</button>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endmacro %}

{% macro activity_panel(events) %}
  <div class="card panel-default">
    <div class="panel-heading">Activity</div>
    <ul class="list-group" style="max-height:400px; overflow-y: scroll;">
      {% for event in events %}
        <li class="list-group-item">
          <strong>{{ event.user_name }}</strong>
          {{ event.verb }}
          <a href="{{ event.link }}">{{ event.subject[0:30] }}</a>
          at <span class="timestamp">{{ event.created_at.date() }}</span>
        </li>
      {% else %}
        <li class="list-group-item">No activity yet</li>
      {% endfor %}
    </ul>
  </div>
{% endmacro %}

{% macro pedigree_panel(case) %}
  <div class="card panel-default">
    <div class="panel-heading">Pedigree</div>
    <div class="card-body">
      <div class="table-responsive">
      {% if case.individuals|length == 1 %}
        <p>Single sample case: {{ case.individuals.0.display_name }}</p>
      {% else %}
        <div class="d-flex justify-content-center align-items-center" >
          <object>
        {{ case.madeline_info|safe }}
          </object>
        </div>
      {% endif %}
      </div>
    </div>
  </div>
{% endmacro %}