apps/scout/scout/server/blueprints/variant/views.py
import logging

from flask import Blueprint, request, redirect, flash, current_app, url_for, jsonify
from flask_login import current_user

from scout.utils.acmg import get_acmg
from scout.server.utils import templated, public_endpoint, institute_and_case
from scout.server.extensions import store, loqusdb
from scout.server.blueprints.variant.controllers import variant as variant_controller
from scout.server.blueprints.variant.controllers import evaluation as evaluation_controller
from scout.server.blueprints.variant.controllers import variant_acmg as acmg_controller
from scout.server.blueprints.variant.controllers import (
    observations,
    variant_acmg_post,
    clinvar_export,
)

from scout.server.blueprints.variant.verification_controllers import (
    variant_verification,
    MissingVerificationRecipientError,
)

from scout.parse.clinvar import set_submission_objects

from scout.constants import ACMG_CRITERIA, ACMG_MAP

LOG = logging.getLogger(__name__)

variant_bp = Blueprint("variant", __name__, static_folder="static", template_folder="templates")


@variant_bp.route("/<institute_id>/<case_name>/<variant_id>")
@templated("variant/variant.html")
def variant(institute_id, case_name, variant_id):
    """Display a specific SNV variant."""
    LOG.debug("Variants view requesting data for variant %s", variant_id)

    data = variant_controller(store, institute_id, case_name, variant_id=variant_id)
    if data is None:
        LOG.warning(
            "An error occurred: variants view requesting data for variant {}".format(variant_id)
        )
        flash("An error occurred while retrieving variant object", "danger")
        return redirect(request.referrer)

    if current_app.config.get("LOQUSDB_SETTINGS"):
        LOG.debug("Fetching loqusdb information for %s", variant_id)
        data["observations"] = observations(store, loqusdb, data["case"], data["variant"])

    return data


@variant_bp.route("/<institute_id>/<case_name>/sv/variants/<variant_id>")
@templated("variant/sv-variant.html")
def sv_variant(institute_id, case_name, variant_id):
    """Display a specific structural variant."""
    data = variant_controller(store, institute_id, case_name, variant_id, add_other=False)

    if current_app.config.get("LOQUSDB_SETTINGS"):
        LOG.debug("Fetching loqusdb information for %s", variant_id)
        data["observations"] = observations(store, loqusdb, data["case"], data["variant"])

    return data


@variant_bp.route("/<institute_id>/<case_name>/str/variants/<variant_id>")
@templated("variant/str-variant.html")
def str_variant(institute_id, case_name, variant_id):
    """Display a specific STR variant."""
    data = variant_controller(
        store, institute_id, case_name, variant_id, add_other=False, get_overlapping=False,
    )

    return data


@variant_bp.route("/<institute_id>/<case_name>/<variant_id>/acmg", methods=["GET", "POST"])
@templated("variant/acmg.html")
def variant_acmg(institute_id, case_name, variant_id):
    """ACMG classification form."""
    if request.method == "GET":
        data = acmg_controller(store, institute_id, case_name, variant_id)
        return data

    criteria = []
    criteria_terms = request.form.getlist("criteria")
    for term in criteria_terms:
        criteria.append(
            dict(
                term=term,
                comment=request.form.get("comment-{}".format(term)),
                links=[request.form.get("link-{}".format(term))],
            )
        )
    acmg = variant_acmg_post(
        store, institute_id, case_name, variant_id, current_user.email, criteria
    )
    flash("classified as: {}".format(acmg), "info")
    return redirect(
        url_for(".variant", institute_id=institute_id, case_name=case_name, variant_id=variant_id,)
    )


@variant_bp.route("/<institute_id>/<case_name>/<variant_id>/update", methods=["POST"])
def variant_update(institute_id, case_name, variant_id):
    """Update user-defined information about a variant: manual rank & ACMG."""
    institute_obj, case_obj = institute_and_case(store, institute_id, case_name)
    variant_obj = store.variant(variant_id)
    user_obj = store.user(current_user.email)
    link = request.referrer

    manual_rank = request.form.get("manual_rank")
    cancer_tier = request.form.get("cancer_tier")
    if manual_rank:
        try:
            new_manual_rank = int(manual_rank) if manual_rank != "-1" else None
        except ValueError:
            LOG.warning("Attempt to update manual rank with invalid value {}".format(manual_rank))
            manual_rank = "-1"
            new_manual_rank = -1

        store.update_manual_rank(
            institute_obj, case_obj, user_obj, link, variant_obj, new_manual_rank
        )
        if new_manual_rank:
            flash("updated variant tag: {}".format(new_manual_rank), "info")
        else:
            flash(
                "reset variant tag: {}".format(variant_obj.get("manual_rank", "NA")), "info",
            )
    elif cancer_tier:
        try:
            new_cancer_tier = cancer_tier if cancer_tier != "-1" else None
        except ValueError:
            LOG.warning("Attempt to update cancer tier with invalid value {}".format(cancer_tier))
            cancer_tier = "-1"
            new_cancer_tier = "-1"

        store.update_cancer_tier(
            institute_obj, case_obj, user_obj, link, variant_obj, new_cancer_tier
        )
        if new_cancer_tier:
            flash("updated variant tag: {}".format(new_cancer_tier), "info")
        else:
            flash(
                "reset variant tag: {}".format(variant_obj.get("cancer_tier", "NA")), "info",
            )
    elif request.form.get("acmg_classification"):
        new_acmg = request.form["acmg_classification"]
        acmg_classification = variant_obj.get("acmg_classification")
        # If there already is a classification and the same one is sent again this means that
        # We want to remove the classification
        if isinstance(acmg_classification, int) and (new_acmg == ACMG_MAP[acmg_classification]):
            new_acmg = None

        store.submit_evaluation(
            variant_obj=variant_obj,
            user_obj=user_obj,
            institute_obj=institute_obj,
            case_obj=case_obj,
            link=link,
            classification=new_acmg,
        )
        flash("updated ACMG classification: {}".format(new_acmg), "info")

    new_dismiss = request.form.getlist("dismiss_variant")
    if new_dismiss:
        store.update_dismiss_variant(
            institute_obj, case_obj, user_obj, link, variant_obj, new_dismiss
        )
        flash("Dismissed variant: {}".format(new_dismiss), "info")

    variant_dismiss = variant_obj.get("dismiss_variant")
    if variant_dismiss and not new_dismiss:
        if "dismiss" in request.form:
            store.update_dismiss_variant(
                institute_obj, case_obj, user_obj, link, variant_obj, new_dismiss
            )
            flash(
                "Reset variant dismissal: {}".format(variant_obj.get("dismiss_variant")), "info",
            )
        else:
            LOG.debug(
                "DO NOT reset variant dismissal: {}".format(",".join(variant_dismiss), "info")
            )

    mosaic_tags = request.form.getlist("mosaic_tags")
    if mosaic_tags:
        store.update_mosaic_tags(institute_obj, case_obj, user_obj, link, variant_obj, mosaic_tags)
        flash("Added mosaic tags: {}".format(mosaic_tags), "info")

    variant_mosaic = variant_obj.get("mosaic_tags")
    if variant_mosaic and not mosaic_tags:
        if "mosaic" in request.form:
            store.update_mosaic_tags(
                institute_obj, case_obj, user_obj, link, variant_obj, mosaic_tags
            )
            flash("Reset mosaic tags: {}".format(",".join(variant_mosaic), "info"))

    return redirect(request.referrer)


@variant_bp.route("/evaluations/<evaluation_id>", methods=["GET", "POST"])
@templated("variant/acmg.html")
def evaluation(evaluation_id):
    """Show or delete an ACMG evaluation."""
    evaluation_obj = store.get_evaluation(evaluation_id)
    evaluation_controller(store, evaluation_obj)
    if request.method == "POST":
        link = url_for(
            ".variant",
            institute_id=evaluation_obj["institute"]["_id"],
            case_name=evaluation_obj["case"]["display_name"],
            variant_id=evaluation_obj["variant_specific"],
        )
        store.delete_evaluation(evaluation_obj)
        return redirect(link)
    return dict(
        evaluation=evaluation_obj,
        institute=evaluation_obj["institute"],
        case=evaluation_obj["case"],
        variant=evaluation_obj["variant"],
        CRITERIA=ACMG_CRITERIA,
    )


@variant_bp.route("/api/v1/acmg")
@public_endpoint
def acmg():
    """Calculate an ACMG classification from submitted criteria."""
    criteria = request.args.getlist("criterion")
    classification = get_acmg(criteria)
    return jsonify(dict(classification=classification))


@variant_bp.route("/<institute_id>/<case_name>/<variant_id>/clinvar", methods=["POST", "GET"])
@templated("variant/clinvar.html")
def clinvar(institute_id, case_name, variant_id):
    """Build a clinVar submission form for a variant."""
    data = clinvar_export(store, institute_id, case_name, variant_id)
    if request.method == "GET":
        return data
    # POST
    form_dict = {}
    # flatten up HPO and OMIM terms lists into string of keys separated by semicolon
    for key, value in request.form.items():
        if key.startswith("conditions@") or key.startswith("clin_features@"):
            conditions = request.form.getlist(key)  # can be HPO or OMIM conditions
            if conditions:
                variant_id = key.split("@")[1]
                cond_types = []
                cond_values = []

                for condition in conditions:
                    cond_types.append(condition.split("_")[0])  # 'HPO' or 'OMIM'

apps/scout/scout/server/blueprints/variant/templates/variant/acmg.html
{% extends "layout_bs4.html" %}

{% block title %}
  {{ super() }} - {{ institute.display_name }} - {{ case.display_name }} - {{ variant.display_name }} - Classify
{% endblock %}

{% block content_main %}
  {% if not evaluation %}
    <div class="float-top-secondary">
      <div class="text-center">
        {% for option in ACMG_OPTIONS %}
          <a id="acmg-{{ option.code }}" class="btn btn-light acmg-preview">{{ option.label }}</a>
        {% endfor %}
      </div>
    </div>
  {% endif %}
  <hr>
  <div class="container mt-3">
    <form action="{{ url_for('variant.variant_acmg', institute_id=institute._id, case_name=case.display_name, variant_id=variant._id) }}" method="POST">
      <div class="card panel-default mt-3">
        <div class="card-body">
          {% if not evaluation %}
            <button class="btn btn-primary form-control">Submit</button>
          {% else %}
            <h4>
              {{ evaluation.classification.label }}
              <span class="badge badge-info">{{ evaluation.classification.short }}</span>
            </h4>
            By {{ evaluation.user_name }} on {{ evaluation.created_at.date() }}
          {% endif %}
        </div>
      </div>

      <div class="d-flex justify-content-between mt-3">
        {% for category, criteria_group in CRITERIA.items() %}
          <div class="flex-1 {{ 'mr-3' if not loop.last }}">
            <h4>Evidence of {{ category }}</h4>
            {% for evidence, criteria in criteria_group.items() %}
              <ul class="list-group mt-3">
                <li class="list-group-item">{{ evidence }}</li>
                {% for criterion_code, criterion in criteria.items() %}

                  {% if evaluation and evaluation.criteria.get(criterion_code).comment %}
                    {% set comment = evaluation.criteria.get(criterion_code).comment %}
                  {% endif %}
                  {% if evaluation and evaluation.criteria.get(criterion_code).links %}
                    {% set link = evaluation.criteria.get(criterion_code).links[0] %}
                  {% endif %}

                  <div class="list-group-item">
                    <div class="d-flex justify-content-between">
                      <div data-toggle="tooltip" data-placement="top" title="{{ criterion.description }}">
                        <span class="badge badge-info mr-1">{{ criterion_code }}</span>
                        {{ criterion.short }}
                      </div>
                      <div>
                        <input type="checkbox" class="ios8-switch" id="checkbox-{{ criterion_code }}" name="criteria" value="{{ criterion_code }}" {{ 'checked' if evaluation and criterion_code in evaluation.criteria }} {{ 'disabled' if evaluation }}>
                        <label for="checkbox-{{ criterion_code }}"></label>
                      </div>
                    </div>
                    <div id="comment-{{ criterion_code }}" class="{{ 'collapse' if not (comment or link) }} mt-2">
                      <div class="form-group">
                        <textarea {{ 'disabled' if comment }} class="form-control"
                          name="comment-{{ criterion_code }}" rows="3" placeholder="Comment (optional)">{{ comment }}</textarea>
                      </div>
                      <input type="url" {{ 'disabled' if link or comment }} class="form-control" name="link-{{ criterion_code }}"
                        placeholder="{{ link or 'Supporting link (optional)' }}" value="">
                    </div>
                  </div>
                {% endfor %}
                </li>
              </ul>
            {% endfor %}
          </div>
        {% endfor %}
      </div>
    </form>
  </div>
{% endblock %}

{% macro preview() %}
  <div class="card panel-default">
    <div class="card-body">
      <span class="text-muted">Classification</span>
      <h5>Likely Pathogenic</h5>
    </div>
  </div>
{% endmacro %}

{% block scripts %}
  {{ super() }}

  <script>
    $(function () {
      $('[data-toggle="tooltip"]').tooltip();

      $('.ios8-switch').change(function(event) {
        var el = $('#comment-' + event.target.value);
        if (event.target.checked) {
          el.collapse('show');
        } else {
          el.collapse('hide');
        }

        update_classification()
      });
    });

    function update_classification() {
      var criteria = $(':checked').map(function(idx, elem) {
        return 'criterion=' + elem.value
      });
      $.getJSON('/api/v1/acmg?' + criteria.toArray().join('&'), function(data) {
        // reset the selection
        $('.acmg-preview').removeClass('btn-primary');
        // add new selection
        $('#acmg-' + data.classification).addClass('btn-primary');
      });
    }
  </script>
{% endblock %}

apps/scout/scout/server/blueprints/variant/templates/variant/buttons.html
{% macro variant_tag_button(variant, institute, case, manual_rank_options) %}
  <form action="{{ url_for('variant.variant_update', institute_id=institute._id, case_name=case.display_name, variant_id=variant._id) }}" method="POST">
    <label class="mt-3">Variant tag</label>
    <div class="row">
      <div class="col-8">
        <select name="manual_rank" class="form-control">
          <option value="-1">Select a tag...</option>
          {% for rank, data in manual_rank_options.items() %}
            <option {% if rank == variant.manual_rank %} selected {% endif %} value="{{ rank }}">
              {{ data.label }}
            </option>
          {% endfor %}
        </select>
      </div>
      <div class="col-4">
        <button type="submit" name="manual_rank" class="btn btn-outline-secondary form-control">Save</button>
      </div>
    </div>
  </form>
{% endmacro %}

{% macro variant_tier_button(variant, institute, case, cancer_tier_options) %}
  <form action="{{ url_for('variant.variant_update', institute_id=institute._id, case_name=case.display_name, variant_id=variant._id) }}" method="POST">
    <label class="mt-3">Variant tier</label>
    <div class="row">
      <div class="col-8">
        <select name="cancer_tier" class="form-control" data-width="100%">
          <option value="-1">Select a tag...</option>
          {% for rank, data in cancer_tier_options.items() %}
            <option {% if rank == variant.cancer_tier %} selected {% endif %} value="{{ rank }}">
              {{ data.label }}
            </option>
          {% endfor %}
        </select>
      </div>
      <div class="col-4">
        <button type="submit" name="manual_rank" class="btn btn-outline-secondary form-control">Save</button>
      </div>
    </div>
  </form>
{% endmacro %}

{% macro dismiss_variant_button(variant, institute, case, dismiss_variant_options) %}
  <form action="{{ url_for('variant.variant_update', institute_id=institute._id, case_name=case.display_name, variant_id=variant._id) }}" method="POST">
    <label class="mt-3">Dismiss variant</label>
    <div class="row">
      <div class="col-8">
        <select multiple="multiple" name="dismiss_variant" id="dismiss_variant" class="selectpicker" data-width="100%">
          {% for rank, data in dismiss_variant_options.items() %}
            <option {% if rank~"" in variant.dismiss_variant %} selected {% endif %} value="{{ rank }}">
              {{ data.label }}
            </option>
          {% endfor %}
        </select>
      </div>
      <div class="col-4">
        <button type="submit" name="dismiss" class="btn btn-outline-secondary form-control">Save</button>
      </div>
    </div>
  </form>
{% endmacro %}

{% macro mosaic_variant_button(variant, institute, case, mosaic_variant_options) %}
  <form action="{{ url_for('variant.variant_update', institute_id=institute._id, case_name=case.display_name, variant_id=variant._id) }}" method="POST">
    <label class="mt-3">Mosaic Tags</label>
    <div class="row">
      <div class="col-8">
        <select multiple="multiple" name="mosaic_tags" id="mosaic_tags" class="selectpicker" data-width="100%">
          {% for rank, data in mosaic_variant_options.items() %}
            <option {% if rank~"" in variant.mosaic_tags %} selected {% endif %} value="{{ rank }}">
              {{ data.label }}
            </option>
          {% endfor %}
        </select>
      </div>
      <div class="col-4">
        <button type="submit" name="mosaic" class="btn btn-outline-secondary form-control">Save</button>
      </div>
    </div>
  </form>
{% endmacro %}

apps/scout/scout/server/blueprints/variant/templates/variant/gene_disease_relations.html
{% macro omim_phenotypes(variant) %}
  <div class="card panel-default">
    <div class="panel-heading">OMIM</div>
    <div class="card-body">
      <div class="table-responsive fixed-panel">
        <table class="table table-bordered table-condensed table-sm">
          <thead class="thead-light">
            <tr>
              <th>Gene</th>
              <th>Phenotype</th>
              <th>Inheritance model</th>
            </tr>
          </thead>
          <tbody>
            {% for gene in variant.genes %}
              {% if gene.common %}
                {% for disease_term in gene.common.phenotypes %}
                  <tr>
                    <td>
                        <a href="http://omim.org/entry/{{ gene.common.omim_id }}" target="_blank">
                          {{ gene.common.hgnc_symbol }}
                        </a>
                    </td>
                    <td>
                      <a href="http://omim.org/entry/{{ disease_term.mim_number|replace('OMIM:', '') }}" target="_blank">
                        {{ disease_term.description }}
                      </a>
                    </td>
                    <td>{{ disease_term.inheritance_models|join(', ') }}</td>
                  </tr>
                {% endfor %}
              {% endif %}
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endmacro %}

{% macro inheritance_panel(variant) %}
  <div class="card panel-default">
    <div class="panel-heading">Gene annotations</div>
    <div class="card-body">
      <ul class="list-group">
        <li class="list-group-item">
          Variant inheritance models
          <span class="float-right">
            {% for model in variant.genetic_models|sort %}
              <span class="badge badge-info">{{ model }}</span>
            {% else %}
              <span class="badge badge-warning">No models followed</span>
            {% endfor %}
          </span>
        </li>
      </ul>
    </div>
  </div>
{% endmacro %}

{% macro autozygosity_panel(variant) %}
  <div class="card panel-default">
    <div class="panel-heading">Autozygous region</div>
    <div class="card-body">
      <table class="table table-bordered table-fixed table-sm">
        <tbody>
          <tr>
            <td>
              Length
              <span class="float-right">{{ variant.azlength }}</span>
            </td>
            <td>
              Qual
              <span class="float-right">{{ variant.azqual }}</span>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
{% endmacro %}

{% macro genemodels_panel(variant) %}
  <div class="card panel-default">
    <div class="panel-heading">Gene models</div>
    <div class="card-body">
      <table class="table table-bordered table-sm">
        <thead class="thead-light">
          <tr>
            <th rowspan="2">Gene</th>
            <th colspan="2">Inheritance</th>
            <th colspan="2">Penetrance</th>
          </tr>
          <tr>
            <th>OMIM</th>
            <th>Manual</th>
            <th>OMIM</th>
            <th>Manual</th>
          </tr>
        </thead>
        <tbody>
          {% for gene in variant.genes %}
            <tr>
              <td>{{ gene.hgnc_symbol }}</td>
              <td>
                {% for model in gene.omim_inheritance %}
                  <span class="badge badge-info">{{ model }}</span>
                {% endfor %}
              </td>
              <td>
                {% for model in gene.manual_inheritance %}
                  <span class="badge badge-info">{{ model }}</span>
                {% endfor %}
              </td>
              <td>
                {% if gene.omim_penetrance %}
                  <span class="badge badge-success">yes</span>
                {% else %}
                  <span class="badge badge-secondary">no</span>
                {% endif %}
              </td>
              <td>
                {% if gene.manual_penetrance %}
                  <span class="badge badge-success">yes</span>
                {% else %}
                  <span class="badge badge-secondary">no</span>
                {% endif %}
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endmacro %}

apps/scout/scout/server/blueprints/variant/templates/variant/variant_details.html
{% macro gtcall_panel(variant) %}
  <div class="card panel-default">
    <div class="panel-heading">
      GT call
      {% if variant.is_par %}
        <span class="badge badge-info">PAR</span>
      {% endif %}
    </div>
    <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th rowspan="2">Sample</th>
            <th rowspan="2">Genotype (GT)</th>
            <th colspan="2" title="Unfiltered count of reads that support a given allele.">Allele depth (AD)</th>
            <th rowspan="2" colspan="1" title="Phred-scaled confidence that the true genotype is the one provided in GT (max=99).">Genotype quality (GQ)</th>
            <tr>
              <th>Reference</th>
              <th>Alternative</th>
            </tr>
          </tr>
        </thead>
        <tbody>
          {% for sample in variant.samples %}
            <tr {{ 'class="danger"' if sample.is_affected }}>
              <td>{{ sample.display_name }}</td>
              <td class="text-center">{{ sample.genotype_call }}</td>
              {% if sample.allele_depths %}
                  {% for number in sample.allele_depths %}
                    <td class="text-right">{{ number }}</td>
                  {% endfor %}
              {% else %}
                  <td class="text-right"><small>N/A</small></td>
                  <td class="text-right"><small>N/A</small></td>
              {% endif %}
              <td class="text-right">{{ sample.genotype_quality }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="panel-footer">
      {% for name, caller in variant.callers %}
        <span class="badge badge-secondary">{{ name }}: {{ caller }}</span>
      {% endfor %}
    </div>
    </div>
  </div>
{% endmacro %}

{% macro frequencies(variant) %}
  <div class="card panel-default">
    <div class="panel-heading">Frequencies</div>
    <div class="card-body">
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th scope="col">Source</th>
            <th scope="col">Frequency</th>
          </tr>
        </thead>
        <tbody>
          {% for freq_name, value, link in variant.frequencies %}
          <tr>
            <td>
              {% if link %}
                <a href="{{ link }}" target="_blank">{{ freq_name }}</a>
              {% else %}
                {{ freq_name }}
              {% endif %}
            </td>
            <td>
              {% if value %}
                <span class="badge badge-secondary">{{ value|human_decimal }}</span>
              {% else %}
                -
              {% endif %}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="card-footer">
      <a href="{{ variant.swegen_link }}" target="_blank">SweGen</a>
      <a href="{{ variant.beacon_link }}" target="_blank">Beacon</a>
      {% if variant.cosmic_link %}
        <a href="{{ variant.cosmic_link }}" target="_blank">COSMIC</a>
      {% else %}
        COSMIC
      {% endif %}
    </div>
  </div>
{% endmacro %}

{% macro observations_panel(variant, observations, case) %}
  <div class="card panel-default">
    <div class="panel-heading">
      <a class="text-white" href="https://github.com/moonso/loqusdb" target="_blank">Local observations</a>
    </div>
    <div class="card-body">
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th scope="col">Nr obs.</th>
            <th scope="col">Nr homo.</th>
            <th scope="col">Total nr.</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>{{ observations.observations|default('N/A') }}</td>
            <td>{{ observations.homozygote|default('N/A') }}</td>
            <td>{{ observations.total }}</td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="card-footer">
      <span title="Shows maximum 10 cases"><strong>Cases</strong></span>
        {% if observations['cases'] %}
          {% for data in observations['cases'] %}
            {% if data.variant %}
              <a class="ml-3" href="{{ url_for('variant.variant', institute_id=data.case.owner, case_name=data.case.display_name, variant_id=data.variant._id) }}">{{ data.case.display_name }}</a>
            {% else %}
              <span class="text-muted ml-3">{{ data.case.display_name }}</span>
            {% endif %}
          {% endfor %}
          {% if observations['cases']|length >= 10 %}
          ...
          {% endif%}
        {% endif %}
    </div>
  </div>
{% endmacro %}

{% macro old_observations(variant, obs_date) %}
  <div class="card panel-default">
    <div class="panel-heading">
      <a class="text-white" href="https://github.com/moonso/loqusdb" target="_blank">Local observations (archive {{obs_date or '2017-05-31'}})</a>
    </div>
    <div class="card-body">
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th scope="col">Nr obs.</th>
            <th scope="col">Nr homo.</th>
            <th scope="col">Total nr.</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>{{ variant.local_obs_old or 'N/A' }}</td>
            <td>{{ variant.local_obs_hom_old or 'N/A' }}</td>
            <td>{{ variant.local_obs_total_old or 638 }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
{% endmacro %}

{% macro severity_list(variant) %}
  <div class="card panel-default">
    <div class="panel-heading">Severity</div>
    <div class="card-body">
      <ul class="list-group">
        <li class="list-group-item">
          <a href="https://sift.bii.a-star.edu.sg/www/SIFT_help.html" target="_blank">SIFT</a>
          <span class="float-right">{{ variant.sift_predictions|join(', ') }}</span>
        </li>
        <li class="list-group-item">
          <a href="https://sites.google.com/site/revelgenomics/about" target="_blank">REVEL</a>
          <span class="float-right">{{ variant.revel_score or "-" }}</span>
        </li>
        <li class="list-group-item">
          <a href="http://genetics.bwh.harvard.edu/pph2/" target="_blank">Polyphen</a>
          <span class="float-right">{{ variant.polyphen_predictions|join(', ') }}</span>
        </li>
        <li class="list-group-item">
          SPIDEX
          <span class="float-right">{{ variant.spidex_human }}</span>
        </li>
      </ul>
    </div>
  </div>
{% endmacro %}

{% macro conservations(variant) %}
  <div class="card panel-default">
    <div class="panel-heading">Conservation</div>
    <div class="card-body">
      <ul class="list-group">
        <li class="list-group-item">
          PHAST
          <span class="float-right">{{ variant.phast_conservation|join(', ') or '-' }}</span>
        </li>
        <li class="list-group-item">
          GERP
          <span class="float-right">{{ variant.gerp_conservation|join(', ') or '-' }}</span>
        </li>
        <li class="list-group-item">
          phyloP
          <span class="float-right">{{ variant.phylop_conservation|join(', ') or '-' }}</span>
        </li>
      </ul>
    </div>
  </div>
{% endmacro %}


{% macro mappability(variant) %}
  <div class="card panel-default">
    <div class="panel-heading">Mappability (<a class="text-white" href="http://genome.ucsc.edu/cgi-bin/hgTrackUi?g=genomicSuperDups" target="_blank">fracMatch</a>)</div>
    {% set superdups_fracmatches = [] %}
    {% for gene in variant.genes %}
      {% for transcript in gene.transcripts %}
        {% if transcript.superdups_fracmatch %}
          {% for superdup in transcript.superdups_fracmatch %}
            {% do superdups_fracmatches.append(superdup) %}
          {% endfor %}
        {% endif %}
      {% endfor %}
    {% endfor %}
    {% set superdups_fracmatches = superdups_fracmatches|sort %}
    <div class="panel-body">
      <ul class="list-group">
        {% if superdups_fracmatches %}
          <li class="list-group-item">
            <span>mapping to {{superdups_fracmatches|length}} segm. dups. (min matching:{{ superdups_fracmatches|first|float|round(3) }}, max matching:{{ superdups_fracmatches|last|float|round(3) }})</span>
          </li>
        {% else %}
          <li class="list-group-item">
            <p class="card-text">-</p>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
{% endmacro %}