apps/scout/scout/server/blueprints/genes/__init__.py
# -*- coding: utf-8 -*-
from .views import genes_bp

apps/scout/scout/server/blueprints/genes/controllers.py
# -*- coding: utf-8 -*-
from pprint import pprint as pp

from scout.server.links import add_gene_links, add_tx_links, omim


def gene(store, hgnc_id):
    """Parse information about a gene."""
    res = {
        "builds": {"37": None, "38": None},
        "symbol": None,
        "description": None,
        "ensembl_id": None,
        "record": None,
    }

    for build in res["builds"]:
        record = store.hgnc_gene(hgnc_id, build=build)
        if record:

            record["position"] = "{this[chromosome]}:{this[start]}-{this[end]}".format(this=record)
            res["aliases"] = record["aliases"]
            res["hgnc_id"] = record["hgnc_id"]
            res["description"] = record["description"]
            res["builds"][build] = record
            res["symbol"] = record["hgnc_symbol"]
            res["description"] = record["description"]
            res["entrez_id"] = record.get("entrez_id")
            res["pli_score"] = record.get("pli_score")

            add_gene_links(record, int(build))

            res["omim_id"] = record.get("omim_id")
            res["incomplete_penetrance"] = record.get("incomplete_penetrance", False)
            res["inheritance_models"] = record.get("inheritance_models", [])
            for transcript in record["transcripts"]:
                transcript["position"] = "{this[chrom]}:{this[start]}-{this[end]}".format(
                    this=transcript
                )
                add_tx_links(transcript, build)

            for phenotype in record.get("phenotypes", []):
                phenotype["omim_link"] = omim(phenotype.get("mim_number"))

            if not res["record"]:
                res["record"] = record

    # If none of the genes where found
    if not any(res.values()):
        raise ValueError

    return res


def genes_to_json(store, query):
    """Fetch matching genes and convert to JSON."""
    gene_query = store.hgnc_genes(query, search=True)
    json_terms = [
        {
            "name": "{} | {} ({})".format(
                gene["hgnc_id"], gene["hgnc_symbol"], ", ".join(gene["aliases"])
            ),
            "id": gene["hgnc_id"],
        }
        for gene in gene_query
    ]
    return json_terms

apps/scout/scout/server/blueprints/genes/views.py
# -*- coding: utf-8 -*-
from flask import abort, Blueprint, request, jsonify, redirect, url_for, flash

from scout.server.extensions import store
from scout.server.utils import templated, public_endpoint
from . import controllers

genes_bp = Blueprint("genes", __name__, template_folder="templates")


@genes_bp.route("/genes")
@templated("genes/genes.html")
def genes():
    """Render seach box for genes."""
    query = request.args.get("query", "")
    hgnc_id = None
    if "|" in query:
        try:
            hgnc_id = int(query.split(" | ", 1)[0])
        except ValueError:
            flash("Provided gene info could not be parsed!", "warning")
    if hgnc_id:
        return redirect(url_for(".gene", hgnc_id=hgnc_id))
    gene_q = store.all_genes(limit=20)
    return dict(genes=gene_q)


@genes_bp.route("/genes/<int:hgnc_id>")
@genes_bp.route("/genes/<hgnc_symbol>")
@templated("genes/gene.html")
def gene(hgnc_id=None, hgnc_symbol=None):
    """Render information about a gene."""
    if hgnc_symbol:
        res = [gene for gene in store.hgnc_genes(hgnc_symbol)]
        if len(res) == 1:
            hgnc_id = res[0]["hgnc_id"]
        else:
            return redirect(url_for(".genes", query=hgnc_symbol))
    try:
        genes = controllers.gene(store, hgnc_id)
    except ValueError as error:
        return abort(404)

    return genes


@genes_bp.route("/api/v1/genes")
@public_endpoint
def api_genes():
    """Return JSON data about genes."""
    query = request.args.get("query")
    json_out = controllers.genes_to_json(store, query)
    return jsonify(json_out)

apps/scout/scout/server/blueprints/genes/templates/genes/gene.html
{% extends "genes/layout.html" %}

{% block title %}
  {{ super() }} - Genes - {{ symbol }}
{% endblock %}

{% block top_nav %}
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('genes.genes') }}">Genes</a>
  </li>
  <li class="nav-item active">
    <span class="navbar-text">{{ symbol }}</span>
  </li>
{% endblock %}

{% block content_main %}
  {{ super() }}

  {# ROW 0 #}
  <div class="row">
    <div class="col-md-12">
      <typeahead url="/api/v1/genes" v-on:send="visitGene" bootstrap="yes"></typeahead>
    </div>
  </div>

  <h1>
    {{ symbol }} <small>{{ record.ensembl_id }}</small>
  </h1>
  <p class="lead">{{ description }}</p>

  <div class="panel panel-default">
    <div class="panel-heading">Common Gene info</div>
        <div class="row">
            <div class="col-md-4">
                <ul class="list-group">
                  <li class="list-group-item">
                    Aliases
                    <span class="float-right">{{ aliases|join(', ') }}</span>
                  </li>
                  <li class="list-group-item">
                    HGNC ID
                    <span class="float-right">
                      <a target="_blank" href={{ record.hgnc_link }} target="_blank"> {{ hgnc_id }}</a>
                    </span>
                  </li>
                  <li class="list-group-item">
                    HGNC symbol
                    <span class="float-right">{{ symbol }}</span>
                  </li>
                  <li class="list-group-item">
                    Description
                    <span class="float-right">{{ description }}</span>
                  </li>
                  <li class="list-group-item">
                    Incomplete penetrance (HPO)
                    <span class="float-right">
                      {{ 'yes' if incomplete_penetrance else 'unknown' }}
                    </span>
                  </li>

                  <li class="list-group-item">
                    Inheritance models
                    <span class="float-right">
                      {{ inheritance_models|join(', ') or '-' }}
                    </span>
                  </li>
            </div>

        <div class="col-md-4">
            <div class="panel panel-default">
              <div class="panel-heading">Links</div>
            <li class="list-group-item">
              OMIM
              <span class="float-right">
                <a target="_blank" href={{ record.omim_link }} target="_blank"> {{ omim_id }}</a>
              </span>
            </li>
            <li class="list-group-item">
              Entrez
              <span class="float-right">
                <a target="_blank" href={{ record.entrez_link }} target="_blank"> {{ entrez_id }}</a>
              </span>
            </li>
            <li class="list-group-item">
              pLi Score(ExAC)
              <span class="float-right">
                <a target="_blank" href={{ record.exac_link }} target="_blank"> {{ pli_score }}</a>
              </span>
            </li>
            <li class="list-group-item">
              Protein Paint
              <span class="float-right">
                <a target="_blank" href={{ record.ppaint_link }} target="_blank"> {{ symbol }}</a>
              </span>
            </li>
            </div>
        </div>

        {% if record.phenotypes %}
        <div class="col-md-4">
            <div class="panel panel-default">
              <div class="panel-heading">Phenotypes</div>

            {% for phenotype in record.phenotypes %}
                <li class="list-group-item">
                    {{ phenotype.description }}
                    <span class="float-right">
                        <a target="_blank" href={{ record.omim_link }} target="_blank"> {{ phenotype.mim_number }}</a>
                    </span>
                </li>
            {% endfor %}
            </div>
        </div>
        {% endif %}

        </div>
</div>


  {% for build, gene in builds.items() %}
  	<div class="panel panel-default">
      <div class="panel-heading">GRCh{{ build }}</div>
	  <div class="panel-body">
	  	{% if gene %}
		  <div class="row">
		    <div class="col-md-6">{{ overview(gene) }}</div>
		    <div class="col-md-6">{{ transcripts(gene) }}</div>
		  </div>
		{% else %}
	      <div>No info for build GRCh{{ build }}.</div>
		{% endif %}
	  </div>
  	</div>
  {% endfor %}
{% endblock %}

{% macro overview(gene) %}
  <ul class="list-group">
    <li class="list-group-item">
      Ensembl ID
      <span class="float-right">
        {%if gene.build == '37'%}
            <a target="_blank" href={{ gene.ensembl_37_link }} target="_blank"> {{ gene.ensembl_id }}</a>
        {% else %}
            <a target="_blank" href={{ gene.ensembl_38_link }} target="_blank"> {{ gene.ensembl_id }}</a>
        {% endif %}
      </span>
    </li>
    <li class="list-group-item">
      Chromosome
      <span class="float-right">{{ gene.chromosome }}</span>
    </li>
    <li class="list-group-item">
      Position
      <span class="float-right">{{ gene.position }}</span>
    </li>
    <li class="list-group-item">
      Expression Atlas
      <span class="float-right">
        <a target="_blank" href={{ gene.expression_atlas_link }} target="_blank"> {{ gene.ensembl_id }}</a>
      </span>
    </li>
    <li class="list-group-item">
      Human Protein Atlas
      <span class="float-right">
        <a target="_blank" href={{ gene.hpa_link }} target="_blank"> {{ gene.ensembl_id }}</a>
      </span>
    </li>
    <li class="list-group-item">
      Reactome
      <span class="float-right">
        <a target="_blank" href={{ gene.reactome_link }} target="_blank"> {{ gene.ensembl_id }}</a>
      </span>
    </li>
    <li class="list-group-item">
      ClinGen
      <span class="float-right">
        <a target="_blank" href={{ gene.clingen_link }} target="_blank"> {{ gene.hgnc_id }}</a>
      </span>
    </li>
    <li class="list-group-item">
      String
      <span class="float-right">
        <a target="_blank" href={{ gene.string_link }} target="_blank"> {{ gene.ensembl_id }}</a>
      </span>
    </li>
    <li class="list-group-item">
      GENEMANIA
      <span class="float-right">
        <a target="_blank" href={{ gene.genemania_link }} target="_blank"> {{ gene.hgnc_symbol }}</a>
      </span>
    </li>
    <li class="list-group-item">
      Vega Database
      <span class="float-right">
        <a target="_blank" href={{ gene.vega_link }} target="_blank"> {{ gene.vega_id }}</a>
      </span>
    </li>
    <li class="list-group-item">
      UCSC gene browser ({{ gene.build }})
      <span class="float-right">
        <a target="_blank" href={{ gene.ucsc_link }} target="_blank"> {{ gene.ucsc_id }}</a>
      </span>
    </li>
  </ul>
{% endmacro %}

{% macro transcripts(gene) %}
  <div class="panel panel-default">
    <div class="panel-heading">Transcripts</div>
    <ul class="list-group list-scroll">
      {% for transcript in gene.transcripts %}
        <li class="list-group-item {{ 'list-group-item-info' if transcript.is_primary }}">
            <a target="_blank" href={{ transcript.ensembl_link }} target="_blank"> {{ transcript.ensembl_transcript_id }}</a>
            /  {{ transcript.refseq_identifiers|join(', ') or '-' }}
            {% if transcript.is_primary %}<small>(primary)</small>{% endif %}
		  <span class="float-right">{{ transcript['position'] }}</span>
        </li>
      {% endfor %}
    </ul>
  </div>
{% endmacro %}

apps/scout/scout/server/blueprints/genes/templates/genes/genes.html
{% extends "genes/layout.html" %}

{% block title %}
  {{ super() }} - Genes
{% endblock %}

{% block top_nav %}
  <li class="nav-item active">
    <span class="navbar-text">Genes</span>
  </li>
{% endblock %}

{% block content_main %}
  {{ super() }}

<div class="container-float">
    <div class="card panel-default w-100 mt-3 justify-content-center">
        <div class="panel-heading">Genes</div>
        <table class="table table-bordered">
          <thead>
            <th>Gene symbol</th>
            <th>HGNC ID</th>
          </thead>
          <tbody>
          {% for gene in genes %}
            <tr>
              <td><a href="{{ url_for('genes.gene', hgnc_symbol=gene.hgnc_id) }}">{{ gene.hgnc_symbol }}</a></td>
              <td>{{ gene.hgnc_id }}</td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
    </div>
</div>
{% endblock %}

apps/scout/scout/server/blueprints/genes/templates/genes/layout.html
{% extends "layout_bs4.html" %}

{% block content_main %}
  <div class="container-float">
    <div class="card mt-3">
      <div class="card-body">
        <form class="form-inline" action="{{ url_for('genes.genes') }}">
          <label for="query">Search for genes</label>
          <div class="form-group">
            <input name="query" class="typeahead form-control mx-sm-5" data-provide="typeahead" autocomplete="off" placeholder="Search...">
            <button class="btn btn-outline-secondary form-control">Search</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

{% block scripts %}
  {{ super() }}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-3-typeahead/4.0.2/bootstrap3-typeahead.min.js"></script>

  <script>
    $(function () {
      function getTerms(query, process) {
        $.get("{{ url_for('genes.api_genes') }}", {query: query}, function(data) {
          process(data)
        });
      }

      $(".typeahead").typeahead({
        source: getTerms,
        minLength: 2,
      });
    })
  </script>
{% endblock %}