apps/scout/scout/server/blueprints/diagnoses/__init__.py
from .views import omim_bp

apps/scout/scout/server/blueprints/diagnoses/controllers.py
# -*- coding: utf-8 -*-


def omim_entry(store, omim_nr):
    """Retrieve specific info for an OMIM term at the gene level

    Args:
        store(obj): an adapter to the scout database
        omim_nr(str): an OMIM disease_nr

    Returns:
        omim_obj(obj): an OMIM term containing description and genes
    """

    omim_obj = store.disease_term(disease_identifier=omim_nr)
    omim_obj["genes_complete"] = store.omim_to_genes(omim_obj)
    omim_obj["hpo_complete"] = [store.hpo_term(hpo_id) for hpo_id in omim_obj.get("hpo_terms", [])]
    return omim_obj

apps/scout/scout/server/blueprints/diagnoses/views.py
from flask import Blueprint

from scout.server.extensions import store
from scout.server.utils import templated, public_endpoint
from . import controllers

omim_bp = Blueprint("diagnoses", __name__, template_folder="templates")


@omim_bp.route("/diagnoses/<omim_nr>", methods=["GET"])
@templated("diagnoses/omim_term.html")
def omim_diagnosis(omim_nr):
    """Display information specific to one OMIM diagnosis"""

    data = controllers.omim_entry(store, omim_nr)
    return data


@omim_bp.route("/diagnoses", methods=["GET"])
@templated("diagnoses/omim_terms.html")
def omim_diagnoses():
    """Display all OMIM diagnoses available in database"""

    data = {"terms": store.disease_terms()}
    return data

apps/scout/scout/server/blueprints/diagnoses/templates/diagnoses/omim_term.html
{% extends "layout_bs4.html" %}

{% block top_nav %}
  <li class="nav-item">
    <a class="nav-link text-nowrap" href="{{ url_for('diagnoses.omim_diagnoses') }}">
      OMIM terms
    </a>
  </li>
  <li class="nav-item active">
    <span class="navbar-text">{{_id}}</span>
  </li>
{% endblock %}

{% block content_main %}
<div class="card mt-3">
  <div class="card-header">Overview</div>
    <div class="card-body">
      <ul class="list-group">
        <li class="list-group-item">
          <a target="_blank" href="http://omim.org/entry/{{ disease_nr }}"># {{disease_nr}}</a>
        </li>
        <li class="list-group-item">
          description: <strong>{{description}}</strong>
        </li>
        <li class="list-group-item">
          genes:
          {% for gene in genes_complete %}
            <span class="badge badge-secondary">{{gene.hgnc_symbol}}</span>
          {% else %}
            -
          {% endfor %}
        </li>
        <li class="list-group-item">
          inheritance:
            {% for model in inheritance %}
              <span class="badge badge-info">{{model}}</span>
            {% else %}
              -
            {% endfor%}
        </li>
        <li class="list-group-item">
          Associated phenotypes:
          <ul class="list-group list-group-flush">
            {% for pheno in hpo_complete %}
              <li class="list-group-item">
                <a href="http://hpo.jax.org/app/browse/term/{{pheno.hpo_id}}" target="_blank">{{ pheno.hpo_id }}</a>
                {{pheno.description}}
              </li>
            {% else %}
              -
            {% endfor %}
          </ul>
        </li>
    </div>
</div>
{% endblock %}

apps/scout/scout/server/blueprints/diagnoses/templates/diagnoses/omim_terms.html
{% extends "layout_bs4.html" %}

{% block css %}
{{ super() }}
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">
  <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.0/css/buttons.dataTables.min.css">
{% endblock %}

{% block top_nav %}
  <li class="nav-item active">
    <span class="navbar-text">OMIM terms</span>
  </li>
{% endblock %}


{% block content_main %}
<div class="container-float">
  <div class="row mt-3">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">OMIM terms</div>
        <div class="card-body">
          {% if terms|length == 0 %}
            The search didn't return any OMIM term
          {% else %}
            <table id="diagnoses_table" class="table table-sm">
              <thead>
                <th>OMIM term</th>
                <th></th>
                <th>Phenotype description</th>
                <th>Inheritance</th>
                <th>Number of associated genes</th>
                <th>Number of associated HPO terms</th>
              </thead>
              {% for omim in terms %}
                <tr>
                  <td><a href="http://omim.org/entry/{{omim.disease_nr}}" target="_blank">{{ omim.disease_nr }}</a></td>
                  <td><a href="{{ url_for('diagnoses.omim_diagnosis', omim_nr=omim.disease_nr) }}"><i class="fa fa-link"></i></a></td>
                  <td>{{ omim.description }}</td>
                  <td><!-- inheritance-->
                    {% for model in omim.inheritance %}
                      <span class="badge badge-info">{{model}}</span>
                    {% else %}
                      -
                    {% endfor %}
                  </td><!--end of inheritance-->
                  <td>{{ omim.genes|length }}</td>
                  <td>{{ omim.hpo_terms|length }}</td>
                </tr>
              {% endfor %}
            </table>
          {% endif %}
        </div><!--end of card body-->
      </div><!--end of card-->
    </div>
  </div>
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.0/js/dataTables.buttons.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.0/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.bootstrap4.min.js"></script>
<script>
  $(document).ready(function() {
    $('#diagnoses_table').DataTable( {
        paging: false,
        dom: 'fBrtip',
        buttons: [
          {
            extend: 'excelHtml5',
            title: 'omim_terms'
          },
          'copyHtml5'
        ]
    } );
} );
</script>
{% endblock %}